apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer-external-service
spec:
  ports:
    - name: http
      port: 3000
      nodePort: 30001
  selector:
    app: kafka-producer
  type: NodePort
