apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: sample-kafka-project
build:
  artifacts:
    - image: kafka-consumer
      context: ./packages/consumer
    - image: kafka-producer
      context: ./packages/producer
deploy:
  kustomize:
    paths:
      - ./k8s/overlays/default
