apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: kafka-consumer
      context: ./packages/consumer
    - image: kafka-producer
      context: ./packages/producer
deploy:
  kustomize:
    path: ./k8s/overlays/default
