apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

bases:
  - ../../bases/kafka
  - ../../bases/zookeeper
  - ../../bases/kafkacat
  - ../../../packages/consumer/k8s/overlays/default
