apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper-service
spec:
  ports:
    - name: client
      port: 2181
    - name: follower
      port: 2888
    - name: leader
      port: 3888
  selector:
    app: zookeeper
