apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer-deployment
spec:
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: kafka-consumer-service-config
          image: kafka-consumer
          name: kafka-consumer
          resources:
            limits:
              cpu: 780m
              memory: 780Mi
            requests:
              cpu: 600m
              memory: 600Mi
      initContainers:
        - args:
            - "-c"
            - until nslookup kafka-service; do echo waiting for kafka-service; sleep 2; done
          command:
            - /bin/sh
          image: "busybox:1.28"
          name: init-kafka
