apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ./deployment.yaml

configMapGenerator:
  - name: kafka-consumer-service-config
    literals:
      - KAFKA_BROKER="kafka-service:9092"
      - KAFKA_TOPIC="todo"
      - KAFKA_CLIENT_ID="todo-consumer"
