apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer-deployment
spec:
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: kafka-producer-service-config
          image: kafka-producer
          name: kafka-producer
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 780m
              memory: 780Mi
            requests:
              cpu: 600m
              memory: 600Mi
      initContainers:
        - args:
            - "-c"
            - until nslookup kafka-service; do echo waiting for kafka-service; sleep 2; done
          command:
            - /bin/sh
          image: "busybox:1.28"
          name: init-kafka
