apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ./deployment.yaml
  - ./service.yaml

configMapGenerator:
  - name: kafka-producer-service-config
    literals:
      - KAFKA_BROKER="kafka-service:9092"
      - KAFKA_TOPIC="todo"
      - KAFKA_CLIENT_ID="todo-producer"
      - SERVER_PORT="3000"
